[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via-ir = true

solc_version = "0.8.26"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@aave/core-v3/=lib/aave-v3-core/"

]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
